### ISSUE TITLE
[todo]: Islands

### ISSUE THREAD

**Issue by ApolloX939** [Beanzilla/adv_sb#1]
The island itself will be one of the 2 schematics (1 for Minetest Game, the other for Mineclone)

I want to support limiting how close islands are placed together (and their Y also must be configurable)

Todo:

- [ ] Built the 2 schematics of an Island
- [ ] Built code that will place a island schematic at X, Z with Y height (Include pre-placement checks, so we can adjust if someone builds a huge island)
- [ ] Built some kind of tracking so we know where islands were placed (prevent placing an island on top of an already existing island)
- [ ] Build support for `/is` `/island` commands (suppport at least sethome, and home... maybe even lock, unlock, and warp to someone else)
- [ ] When a player joins and doesn't have an island one should be generated for them and they be teleported there, also include some configured items they will get when they start off.
- [ ] Release
