### ISSUE TITLE
[todo]: Ore generator

### ISSUE THREAD

**Issue by ApolloX939** [Beanzilla/adv_sb#2]
A node which will produce a random node regarding where it's facing.

Can be upgraded with resources to produce faster.

Todo:

- [ ] Built a node which can produce a random set of nodes
- [ ] Built it so each ore generator is separate to another (They must be separate so a player can't place a bunch that spawn incredibility fast)
- [ ] Support them being upgraded by resources. (Diamond blocks for example would be a good method of upgrading them)
- [ ] Support crafting them. (They must be craft-able by either some of the resources they produce or no one could build on their islands)
- [ ] Release
